[build]
  command = "npm install && npm run build"
  publish = "/"

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200

[[redirects]]
  from = "/gallery"
  to = "/gallery.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301
